Vagrant.configure("2") do |config|

  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    
    # these are somewhat private, so you have to fill in :)
	aws.access_key_id = "xxxxxxxxxxxxxxxxxxxx"
    aws.secret_access_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    aws.keypair_name = "xxxxxxxxxx"
    override.ssh.private_key_path = "xxxxxxxxxx.pem"

    # eu-central-1; ubuntu trusty (14.04) LTS amd64 instance-store  
    aws.region = "eu-central-1"
	aws.ami = "ami-40989b5d"

    # as user 'vagrant' will not work
	override.ssh.username = "ubuntu"
  end
  
  config.vm.provision "docker" do |d|
    d.pull_images "jboss/wildfly"
    d.run "wild1",
      image: "jboss/wildfly",
      args: "-d -p 8081:8080"
    d.run "wild2",
      image: "jboss/wildfly",
      args: "-d -p 8082:8080"        
  end  
  
end


