Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082

  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
  end

  # The following section is used when working with proxy
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://10.55.76.15:8080"
    config.proxy.https    = "https://10.55.76.15:8080"
    config.proxy.no_proxy = "localhost,127.0.0.1"
    
    # special handling of docker because it is still not installed and 'vagrant-proxyconf' does not configure it
    docker_proxy = 'printf "export http_proxy=$http_proxy\n" >> /etc/default/docker'
    config.vm.provision('shell', inline: docker_proxy)
  end


  config.vm.provision "docker" do |d|
    d.pull_images "nats"
    d.pull_images "jboss/wildfly"
    d.run "nats",
      image: "nats",
      args: "-d -p 6222:6222 -p 4222:4222 -p 8222:8222"
    d.run "wild1",
      image: "jboss/wildfly",
      args: "-d -p 8081:8080"
    d.run "wild2",
      image: "jboss/wildfly",
      args: "-d -p 8082:8080"        
  end
end